#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Mar 13 16:20:41 2023

@author: jwt30
"""

import mne

run01_file = '/autofs/cluster/transcend/MEG/AttenAud/075801/visit_20230311/075801_AttenAud_run01_raw.fif'
run01 = mne.io.read_raw_fif(run01_file)
run01events = mne.find_events(run01, stim_channel='STI101',shortest_event=1)
event_list = run01events[:,2]
events=event_list.tolist()

run02_file = '/autofs/cluster/transcend/MEG/AttenAud/075801/visit_20230311/075801_AttenAud_run02_raw.fif'
run02 = mne.io.read_raw_fif(run02_file)
run02events = mne.find_events(run02, stim_channel='STI101',shortest_event=1)
event_list2 = run02events[:,2]
events2=event_list2.tolist()


participant_file = '/autofs/cluster/transcend/MEG/AttenVis/111501/visit_20230203/111501_AttenVis_run03_raw.fif'
participant = mne.io.read_raw_fif(participant_file)
participant_events = mne.find_events(participant, stim_channel='STI101',shortest_event=1)

earlier_participant_file = '/autofs/cluster/transcend/MEG/AttenAud/110101/visit_20220930/110101_AttenAud_run02_raw.fif'
earlier_participant = mne.io.read_raw_fif(earlier_participant_file)
earlier_participant_events = mne.find_events(earlier_participant, stim_channel='STI101',output='step',shortest_event = 1, min_duration= 0.002)
event_sample_number = earlier_participant_events[:,0]
events_earlier_participant =  earlier_participant_events[:,2].tolist()


import numpy
v = numpy.diff(event_sample_number)


from matplotlib import pyplot as plt
fig, axs = plt.subplots(1, 1,
                        figsize =(10, 7),
                        tight_layout = True)
axs.hist(v, bins = 20)

bad_triggers = []
bad_triggers.append(0)
for i in v:
    if i < 200:
        bad_triggers.append(1)
    else: bad_triggers.append(0)
        
    
bad_triggers = numpy.array(bad_triggers)
B = numpy.reshape(bad_triggers, (bad_triggers.size,1))
    
all_data = list(zip(events_earlier_participant, bad_triggers))
data = numpy.append(earlier_participant_events,B, axis = 1)
for interval in v:
    if interval < 200:
        earlier_participant_events[i+1,4]=1
    else: earlier_participant_events[i+1,4]=0
        
test_buttons_file = '/autofs/space/megraid_research/MEG/tal/subj_unknown/230316/button_press_test_right_blue_etc_raw.fif'    
test_buttons = mne.io.read_raw_fif(test_buttons_file)
test_buttons_events = mne.find_events(test_buttons, stim_channel='STI101',shortest_event=1)

test_buttons_file = '/autofs/space/megraid_research/MEG/tal/subj_test_buttons/230317/pilot_sergio.fif'    
test_buttons = mne.io.read_raw_fif(test_buttons_file)
test_buttons_events = mne.find_events(test_buttons, stim_channel='STI101',shortest_event=1)

event_list = test_buttons_events[:,2].tolist()
eoi = [i for i in event_list if i < 100] 

file = '/autofs/cluster/transcend/MEG/AttenAud/098501/098501_AttenAud_run02_raw.fif'
raw = mne.io.read_raw_fif(file)
events = mne.find_events(raw, stim_channel='STI101',output='step',shortest_event=1)